version: '3'
services:
  ravendb:
    container_name: ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
      - 38888:38888
    volumes:
      - ./data:/var/lib/ravendb/data/
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_PublicServerUrl=http://localhost:8080"