export enum CategoryEnum {
  gods = 'gods',
  numbers = 'numbers',
  family = 'family',
  animals = 'animals',
  colors = 'colors',
  food = 'food',
  body = 'body',
  symbols = 'symbols',
  greetings = 'greetings',
  time = 'time',
  nature = 'nature',
  emotions = 'emotions',
  clothes = 'clothes',
  music = 'music',
  home = 'home',
}
